# Generated by Django 4.2.5 on 2023-09-27 08:18

import api_news.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_news', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=api_news.models.get_account, on_delete=django.db.models.deletion.CASCADE, to='api_news.account'),
        ),
    ]
